# Generated by Django 5.0.6 on 2024-06-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_booktournow_contacts_discovernewhorizon_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='icon',
            field=models.CharField(default='fl-bigmug-line-equalization3', max_length=100),
        ),
        migrations.AlterField(
            model_name='hottours',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
