# Generated by Django 5.0.6 on 2024-06-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_headerfooter_swiper_alter_discovernewhorizon_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createyourtourstyle',
            name='style_photo',
            field=models.ImageField(blank=True, null=True, upload_to='createyourtourstyle/%Y/%m/%d/'),
        ),
    ]
