# Generated by Django 5.0.6 on 2024-06-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_createyourtourstyle_style_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='createyourtourstyle',
            name='slug',
            field=models.SlugField(default=True, unique=True),
        ),
    ]
