# Generated by Django 5.0.6 on 2024-06-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_createyourtourstyle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createyourtourstyle',
            name='buttonname',
            field=models.CharField(max_length=100),
        ),
    ]
