# Generated by Django 5.0.6 on 2024-06-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_createyourtourstyle_buttonname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createyourtourstyle',
            name='slug',
            field=models.SlugField(default=True),
        ),
    ]
