# Generated by Django 5.0.6 on 2024-06-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_createyourtourstyle_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createyourtourstyle',
            name='slug',
        ),
    ]
