# Generated by Django 5.0.6 on 2024-06-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_remove_createyourtourstyle_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discovernewhorizon',
            options={'ordering': ('name',), 'verbose_name': 'Discover New Horizon', 'verbose_name_plural': 'Discover New Horizons'},
        ),
        migrations.RenameField(
            model_name='discovernewhorizon',
            old_name='text_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='discovernewhorizon',
            old_name='text_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='discovernewhorizon',
            name='name_of_class',
        ),
        migrations.AddField(
            model_name='createyourtourstyle',
            name='slug',
            field=models.SlugField(default=True),
        ),
    ]
