# Generated by Django 5.0.4 on 2024-08-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_discovernewhorizon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiper',
            options={'ordering': ('text12',), 'verbose_name': 'Swiper', 'verbose_name_plural': 'Swipers'},
        ),
    ]
